server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Or update for quick development, but validate is safer for tests with Flyway
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # For H2 to behave more like PostgreSQL (if your prod DB is Postgres)
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    clean-disabled: false # Crucial for testing: allows flyway.clean()
    baseline-on-migrate: true # Useful if you're managing an existing schema
    # If your migration scripts are in a non-default location, specify here
    # locations: classpath:db/migration
